=== jelly/zarafa-webapp/server/manifest.dtd
<!-- The <plugin> element. This is the root element for the document -->
<!ELEMENT plugin (info,config?,dependencies?,translations?,components)>

	<!-- The <info> element. Positioned inside the <plugin> and/or <component> elements. Provides meta information -->
	<!ELEMENT info (version?,name,title?,author?,authorURL?,description?)>
		<!ELEMENT version (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT authorURL (#PCDATA)>
		<!ELEMENT description (#PCDATA)>

	<!-- The <config> element. Positioned inside the <plugin> element. Provides the location of the configuration file(s) -->
	<!ELEMENT config (configfile+)>
		<!ELEMENT configfile (#PCDATA)>

	<!-- The <dependencies> element. Positioned inside the <plugin> element. Provides the plugin dependencies -->
	<!ELEMENT dependencies (depends+)>
		<!ELEMENT depends (dependsname)>
			<!ELEMENT dependsname (#PCDATA)>

	<!-- The <translations> element. Positioned inside the <plugin> element. Provides the translations information -->
	<!ELEMENT translations (translationsdir+)>
		<!ELEMENT translationsdir (#PCDATA)>

	<!-- The <components> element. Positioned inside the <plugin> element. Provides the components -->
	<!ELEMENT components (component+)>
		<!ELEMENT component (info?,files)>
			<!ELEMENT files (server?,client?,resources?)>
				<!ELEMENT server (serverfile+)>
					<!ELEMENT serverfile (#PCDATA)>
				<!ELEMENT client (clientfile+)>
					<!ELEMENT clientfile (#PCDATA)>
				<!ELEMENT resources (resourcefile+)>
					<!ELEMENT resourcefile (#PCDATA)>

<!-- The attributes for the <plugin> element. -->
<!ATTLIST plugin version CDATA #REQUIRED>

<!-- The attributes for the <depends> element. -->
<!ATTLIST depends type (depends|requires|recommends|suggests) "depends">

<!-- The attributes for the <serverfile> element. -->
<!ATTLIST serverfile load (release|debug|source) "release">
<!ATTLIST serverfile type (plugin|module|notifier) "plugin">
<!ATTLIST serverfile module CDATA #IMPLIED> 
<!ATTLIST serverfile notifier CDATA #IMPLIED> 

<!-- The attributes for the <clientfile> element. -->
<!ATTLIST clientfile load (release|debug|source) "release">

<!-- The attributes for the <resourcefile> element. -->
<!ATTLIST resourcefile load (release|debug|source) "release">

=== jelly/zarafa-webapp/plugins/spreed/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.3</version>
		<name>spreed</name>
		<title>Zarafa Spreed Integration</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Zarafa Spreed Integration, allows you to set-up a conference call from within emails, contact groups, or single contact cards.</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.spreed.php</serverfile>
					<serverfile type="module" module="spreedmodule">php/class.spreedmodule.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/spreed.js</clientfile>
					<clientfile load="debug">js/spreed-debug.js</clientfile>
					<clientfile load="source">js/SpreedPlugin.js</clientfile>
					<clientfile load="source">js/dialogs/EditSpreedParticipantContentPanel.js</clientfile>
					<clientfile load="source">js/dialogs/SpreedParticipantBox.js</clientfile>
					<clientfile load="source">js/dialogs/SpreedParticipantContextMenu.js</clientfile>
					<clientfile load="source">js/dialogs/SpreedParticipantField.js</clientfile>
					<clientfile load="source">js/dialogs/SpreedSetupContentPanel.js</clientfile>
					<clientfile load="source">js/dialogs/SpreedSetupPanel.js</clientfile>
					<clientfile load="source">js/dialogs/SpreedToolBar.js</clientfile>
					<clientfile load="source">js/data/SpreedAttachmentRecord.js</clientfile>
					<clientfile load="source">js/data/SpreedAttachmentStore.js</clientfile>
					<clientfile load="source">js/data/SpreedJsonAttachmentWriter.js</clientfile>
					<clientfile load="source">js/data/SpreedJsonParticipantWriter.js</clientfile>
					<clientfile load="source">js/data/SpreedLanguages.js</clientfile>
					<clientfile load="source">js/data/SpreedParticipantRecord.js</clientfile>
					<clientfile load="source">js/data/SpreedParticipantStore.js</clientfile>
					<clientfile load="source">js/data/SpreedRecord.js</clientfile>
					<clientfile load="source">js/data/SpreedStore.js</clientfile>
					<clientfile load="source">js/data/SpreedTimezones.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/spreed.css</resourcefile>
					<resourcefile load="source">resources/css/plugin.spreedstyles.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/statslogging/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.1</version>
		<name>statslogging</name>
		<title>User Interface Statistics Logging</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Logging of the user inferface interaction statistics</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.statslogging.php</serverfile>
					<serverfile type="module" module="pluginstatsloggingmodule">php/class.pluginstatsloggingmodule.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/statslogging.js</clientfile>
					<clientfile load="debug">js/statslogging-debug.js</clientfile>
					<clientfile load="source">js/StatsLogging.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/facebookwidget/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>facebookwidget</name>
		<title>Facebook widget</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Facebook widget</description>
	</info>
	<components>
		<component>
			<files>
				<client>
					<clientfile load="release">js/facebookwidget.js</clientfile>
					<clientfile load="debug">js/facebookwidget-debug.js</clientfile>
					<clientfile load="source">js/FBWidget.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/pdfbox/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>pdfbox</name>
		<title>PDF attachments preview</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Default viewer for PDF document attachments, this will open the document in a lightbox</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<info>
				<name>pdf.js</name>
				<title>pdf.js</title>
				<author>2011 Mozilla Foundation</author>
				<authorURL>https://github.com/mozilla/pdf.js</authorURL>
				<description>pdf.js is an HTML5 technology experiment that explores building a faithful and efficient Portable Document Format (PDF) renderer without native code assistance.</description>
			</info>
			<files>
				<client>
					<clientfile>pdfjs/compatibility.js</clientfile>
					<clientfile>pdfjs/pdf.js</clientfile>
				</client>
			</files>
		</component>
		<component>
			<info>
				<name>pdfbox</name>
				<title>PdfBox</title>
				<author>Zarafa</author>
				<authorURL>http://www.zarafa.com/</authorURL>
				<description>Library for rendering PDFs in a lightbox. Based on Sencha's Lightbox plugin.</description>
			</info>
			<files>
				<client>
					<clientfile>pdfbox/pdfbox.js</clientfile>
				</client>
				<resources>
					<resourcefile>resources/css/pdfbox.css</resourcefile>
				</resources>
			</files>
		</component>
		<component>
			<info>
				<name>pdfboxplugin</name>
				<title>PdfBoxPlugin</title>
				<author>Zarafa</author>
				<description>A Zarafa plugin enabling the use of PdfBox for opening PDF attachments in e-mails.</description>
			</info>
			<files>
				<server>
					<serverfile>php/plugin.pdfbox.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/pdfbox.js</clientfile>
					<clientfile load="debug">js/pdfbox-debug.js</clientfile>
					<clientfile load="source">js/PdfBoxPlugin.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/folderwidgets/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>folderwidgets</name>
		<title>Folder widgets</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>A collection of widgets which can show the contents of some of the default folders for a user.</description>
	</info>
	<components>
		<component>
			<files>
				<client>
					<clientfile load="release">js/folderwidgets.js</clientfile>
					<clientfile load="debug">js/folderwidgets-debug.js</clientfile>
					<clientfile load="source">js/AbstractFolderWidget.js</clientfile>
					<clientfile load="source">js/AppointmentsWidget.js</clientfile>
					<clientfile load="source">js/TasksWidget.js</clientfile>
					<clientfile load="source">js/MailWidget.js</clientfile>
				</client>
				<resources>
					<resourcefile>resources/css/folderwidgets.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/twidget/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.2</version>
		<name>twidget</name>
		<title>Twidget</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Display twitter feed of currently selected email</description>
	</info>
	<components>
		<component>
			<files>
				<client>
					<clientfile load="release">jsonp/jsonp.js</clientfile>
				</client>
			</files>
		</component>
		<component>
			<files>
				<client>
					<clientfile load="release">js/twidget.js</clientfile>
					<clientfile load="debug">js/twidget-debug.js</clientfile>
					<clientfile load="source">js/Twidget.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>
