=== jelly/zarafa-webapp/server/manifest.dtd
<!-- The <plugin> element. This is the root element for the document -->
<!ELEMENT plugin (info,config?,dependencies?,translations?,components)>

	<!-- The <info> element. Positioned inside the <plugin> and/or <component> elements. Provides meta information -->
	<!ELEMENT info (version?,name,title?,author?,authorURL?,description?)>
		<!ELEMENT version (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT authorURL (#PCDATA)>
		<!ELEMENT description (#PCDATA)>

	<!-- The <config> element. Positioned inside the <plugin> element. Provides the location of the configuration file(s) -->
	<!ELEMENT config (configfile+)>
		<!ELEMENT configfile (#PCDATA)>

	<!-- The <dependencies> element. Positioned inside the <plugin> element. Provides the plugin dependencies -->
	<!ELEMENT dependencies (depends+)>
		<!ELEMENT depends (dependsname)>
			<!ELEMENT dependsname (#PCDATA)>

	<!-- The <translations> element. Positioned inside the <plugin> element. Provides the translations information -->
	<!ELEMENT translations (translationsdir+)>
		<!ELEMENT translationsdir (#PCDATA)>

	<!-- The <components> element. Positioned inside the <plugin> element. Provides the components -->
	<!ELEMENT components (component+)>
		<!ELEMENT component (info?,files)>
			<!ELEMENT files (server?,client?,resources?)>
				<!ELEMENT server (serverfile+)>
					<!ELEMENT serverfile (#PCDATA)>
				<!ELEMENT client (clientfile+)>
					<!ELEMENT clientfile (#PCDATA)>
				<!ELEMENT resources (resourcefile+)>
					<!ELEMENT resourcefile (#PCDATA)>

<!-- The attributes for the <plugin> element. -->
<!ATTLIST plugin version CDATA #REQUIRED>

<!-- The attributes for the <depends> element. -->
<!ATTLIST depends type (depends|requires|recommends|suggests) "depends">

<!-- The attributes for the <serverfile> element. -->
<!ATTLIST serverfile load (release|debug|source) "release">
<!ATTLIST serverfile type (plugin|module|notifier) "plugin">
<!ATTLIST serverfile module CDATA #IMPLIED> 
<!ATTLIST serverfile notifier CDATA #IMPLIED> 

<!-- The attributes for the <clientfile> element. -->
<!ATTLIST clientfile load (release|debug|source) "release">

<!-- The attributes for the <resourcefile> element. -->
<!ATTLIST resourcefile load (release|debug|source) "release">

=== jelly/zarafa-webapp/plugins/dropboxattachment/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.2</version>
		<name>dropboxattachment</name>
		<title>Dropbox Attachment</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Allow the user to attach the files from Dropbox to email.</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile type="module" module="dropboxmodule">php/class.dropboxmodule.php</serverfile>
					<serverfile>php/plugin.dropboxattachment.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/dropboxattachment.js</clientfile>
					<clientfile load="debug">js/dropboxattachment-debug.js</clientfile>
					<clientfile load="source">js/DropboxAttachmentPlugin.js</clientfile>
					<clientfile load="source">js/dialogs/AttachmentContentPanel.js</clientfile>
					<clientfile load="source">js/dialogs/AttachmentTreePanel.js</clientfile>
					<clientfile load="source">js/data/TreeLoader.js</clientfile>
					<clientfile load="source">js/data/ResponseHandler.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/dropboxattachment.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/gmaps/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>gmaps</name>
		<title>Google Maps Plugin</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Shows contact address on google maps.</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.gmaps.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/gmaps.js</clientfile>
					<clientfile load="debug">js/gmaps-debug.js</clientfile>
					<clientfile load="source">js/GmapsPlugin.js</clientfile>
					<clientfile load="source">js/GmapsTab.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/xmpp/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.1</version>
		<name>xmpp</name>
		<title>XMPP plugin</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Implementing the XMPP based chat client for the Zarafa WebApp</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<info>
				<name>jsjac</name>
				<title>JSJaC</title>
				<author>Stefan Strigler</author>
				<authorURL>http://zeank.in-berlin.de/jsjac/</authorURL>
				<description>JavaScript Jabber Client Library</description>
			</info>
			<files>
				<client>
					<clientfile load="release">jsjac/jsjac.js</clientfile>
					<clientfile load="debug">jsjac/jsjac.uncompressed.js</clientfile>
				</client>
			</files>
		</component>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.xmpp.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/xmpp.js</clientfile>
					<clientfile load="debug">js/xmpp-debug.js</clientfile>
					<clientfile load="source">js/XmppChatManager.js</clientfile>
					<clientfile load="source">js/XmppNotificationPlugin.js</clientfile>
					<clientfile load="source">js/XmppPresence.js</clientfile>
					<clientfile load="source">js/XmppRosterEntry.js</clientfile>
					<clientfile load="source">js/XmppVCard.js</clientfile>
					<clientfile load="source">js/XmppChat.js</clientfile>
					<clientfile load="source">js/XmppChatMessage.js</clientfile>
					<clientfile load="source">js/XmppPlugin.js</clientfile>
					<clientfile load="source">js/XmppPreviewPanelPlugin.js</clientfile>
					<clientfile load="source">js/XmppRosterManager.js</clientfile>
					<clientfile load="source">js/XmppWidget.js</clientfile>
					<clientfile load="source">js/data/XmppChatStore.js</clientfile>
					<clientfile load="source">js/data/XmppRosterStore.js</clientfile>
					<clientfile load="source">js/ui/XmppChatPanel.js</clientfile>
					<clientfile load="source">js/ui/XmppChatTabPanel.js</clientfile>
					<clientfile load="source">js/ui/XmppRosterPanel.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
				<resources>
					<resourcefile>resources/css/xmpp.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/facebook/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>facebook</name>
		<title>Zarafa Facebook Integration</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Zarafa Facebook Integration, allows you to import your Facebook events to Zarafa calendar.</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.facebook.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/facebook.js</clientfile>
					<clientfile load="debug">js/facebook-debug.js</clientfile>
					<clientfile load="source">js/FacebookEventsPlugin.js</clientfile>
					<clientfile load="source">js/FbEventSelectionContentPanel.js</clientfile>
					<clientfile load="source">js/FbIntegrationContentPanel.js</clientfile>
					<clientfile load="source">js/FbEventSelectionGrid.js</clientfile>
					<clientfile load="source">js/FbIntegrationPanel.js</clientfile>
					<clientfile load="source">js/data/FbEventDataReader.js</clientfile>
					<clientfile load="source">js/data/FbEventProxy.js</clientfile>
					<clientfile load="source">js/data/FbEventRecord.js</clientfile>
					<clientfile load="source">js/data/FbEventStore.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/facebook.css</resourcefile>
					<resourcefile load="source">resources/css/plugin.facebookstyles.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/example/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.1</version>
		<name>example</name>
		<title>exaple title</title>
		<author>example author</author>
		<authorURL>http://www.example.com</authorURL>
		<description>example description</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile type="module" module="pluginexamplemodule">php/class.pluginexamplemodule.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/example.js</clientfile>
					<clientfile load="debug">js/example-debug.js</clientfile>
					<clientfile load="source">js/Example.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/extbox/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>extbox</name>
		<title>Image attachments preview</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Default viewer for image attachments, this will open the image in a lightbox</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<info>
				<name>lightbox</name>
				<title>Lightbox</title>
				<author>Sencha</author>
				<authorURL>http://http://www.sencha.com/</authorURL>
				<description>Library for rendering images in a lightbox</description>
			</info>
			<files>
				<client>
					<clientfile>lightbox/lightbox.js</clientfile>
				</client>
				<resources>
					<resourcefile>resources/css/lightbox.css</resourcefile>
				</resources>
			</files>
		</component>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.extbox.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/extbox.js</clientfile>
					<clientfile load="debug">js/extbox-debug.js</clientfile>
					<clientfile load="source">js/ExtBoxPlugin.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/browsercompatibility/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.3</version>
		<name>browsercompatibility</name>
		<title>Browser Compatibility Plugin</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Browser Compatibility Testing</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.browsercompatibility.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/browsercompatibility.js</clientfile>
					<clientfile load="debug">js/browsercompatibility-debug.js</clientfile>
					<clientfile load="source">js/BrowserCompatibility.js</clientfile>
					<clientfile load="source">js/BrowserDetect.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/clockwidget/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>1.1</version>
		<name>clockwidget</name>
		<title>Clock Widget</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Displays a clock in the WebApp Dashboard</description>
	</info>
	<components>
		<component>
			<files>
				<client>
					<clientfile load="release">js/clockwidget.js</clientfile>
					<clientfile load="debug">js/clockwidget-debug.js</clientfile>
					<clientfile load="source">js/ClockWidget.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>
