=== jelly/zarafa-webapp/server/manifest.dtd
<!-- The <plugin> element. This is the root element for the document -->
<!ELEMENT plugin (info,config?,dependencies?,translations?,components)>

	<!-- The <info> element. Positioned inside the <plugin> and/or <component> elements. Provides meta information -->
	<!ELEMENT info (version?,name,title?,author?,authorURL?,description?)>
		<!ELEMENT version (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT authorURL (#PCDATA)>
		<!ELEMENT description (#PCDATA)>

	<!-- The <config> element. Positioned inside the <plugin> element. Provides the location of the configuration file(s) -->
	<!ELEMENT config (configfile+)>
		<!ELEMENT configfile (#PCDATA)>

	<!-- The <dependencies> element. Positioned inside the <plugin> element. Provides the plugin dependencies -->
	<!ELEMENT dependencies (depends+)>
		<!ELEMENT depends (dependsname)>
			<!ELEMENT dependsname (#PCDATA)>

	<!-- The <translations> element. Positioned inside the <plugin> element. Provides the translations information -->
	<!ELEMENT translations (translationsdir+)>
		<!ELEMENT translationsdir (#PCDATA)>

	<!-- The <components> element. Positioned inside the <plugin> element. Provides the components -->
	<!ELEMENT components (component+)>
		<!ELEMENT component (info?,files)>
			<!ELEMENT files (server?,client?,resources?)>
				<!ELEMENT server (serverfile+)>
					<!ELEMENT serverfile (#PCDATA)>
				<!ELEMENT client (clientfile+)>
					<!ELEMENT clientfile (#PCDATA)>
				<!ELEMENT resources (resourcefile+)>
					<!ELEMENT resourcefile (#PCDATA)>

<!-- The attributes for the <plugin> element. -->
<!ATTLIST plugin version CDATA #REQUIRED>

<!-- The attributes for the <depends> element. -->
<!ATTLIST depends type (depends|requires|recommends|suggests) "depends">

<!-- The attributes for the <serverfile> element. -->
<!ATTLIST serverfile load (release|debug|source) "release">
<!ATTLIST serverfile type (plugin|module|notifier) "plugin">
<!ATTLIST serverfile module CDATA #IMPLIED> 
<!ATTLIST serverfile notifier CDATA #IMPLIED> 

<!-- The attributes for the <clientfile> element. -->
<!ATTLIST clientfile load (release|debug|source) "release">

<!-- The attributes for the <resourcefile> element. -->
<!ATTLIST resourcefile load (release|debug|source) "release">

=== jelly/zarafa-webapp/plugins/zperformance/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>zperformance</name>
		<title>Zarafa Performance Plugin</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Assistence for measuring performance.</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.zperformance.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/zperformance.js</clientfile>
					<clientfile load="debug">js/zperformance-debug.js</clientfile>
					<clientfile load="source">js/ZPerformance.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/shellgame/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>shellgame</name>
		<title>Shell Game</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>A nice shellgame</description>
	</info>
	<components>
		<component>
			<files>
				<client>
					<clientfile load="release">js/shellgame.js</clientfile>
					<clientfile load="debug">js/shellgame-debug.js</clientfile>
					<clientfile load="source">js/ShellGamePanel.js</clientfile>
					<clientfile load="source">js/ShellGamePlayFieldPanel.js</clientfile>
					<clientfile load="source">js/ShellGameStates.js</clientfile>
					<clientfile load="source">js/ShellGameWidget.js</clientfile>
				</client>
				<resources>
					<resourcefile>resources/css/shellgame.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/salesforce/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>salesforce</name>
		<title>Salesforce</title>
		<author>Sushko Dmitriy - Dyachkov Vlad</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Allow the user to attach the files from DropBox to email.</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<!--<serverfile type="module" module="dropboxmodule">php/class.dropboxmodule.php</serverfile>-->
					<serverfile>php/plugin.salesforce.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/salesforce.js</clientfile>
					<clientfile load="debug">js/salesforce-debug.js</clientfile>
					<clientfile load="source">js/SalesforcePlugin.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/salesforce.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/oauthlib/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
    <info>
        <version>1.1</version>
        <name>oauthlib</name>
        <title>OAuth v2.0 protocol library</title>
        <author>Zarafa</author>
        <authorURL>http://www.zarafa.com</authorURL>
        <description>Allows you to easily create your own API classes which utilizes the OAuth authentication.</description>
    </info>
    <components>
        <component>
            <files>
                <server>
                    <serverfile>php/OAuth2.inc</serverfile>
                    <serverfile>php/OAuth2Client.inc</serverfile>
                    <serverfile>php/OAuth2Exception.inc</serverfile>
                </server>
            </files>
        </component>
    </components>
</plugin>

=== jelly/zarafa-webapp/plugins/feedback/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>feedback</name>
		<title>Feedback collector plugin</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Adds a 'got feedback' button so all users
		  can give feedback directly to Zarafa.</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.feedback.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/feedback.js</clientfile>
					<clientfile load="debug">js/feedback-debug.js</clientfile>
					<clientfile load="source">js/jiratrigger.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/webodf/manifest.xml
<?xml version = "1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version = "2">
	<info>
		<version>0.2</version>
		<name>webodfbox</name>
		<title>WebODF Documents attachment preview</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Shows the Attached WebODF Documents in webapp</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<info>
				<name>webodf.js</name>
				<title>webodf.js</title>
				<author>2011 KO GmbH The Open Document Company</author>
				<authorURL>https://gitorious.org/webodf/webodf</authorURL>
				<description>WebODF is a JavaScript library that makes it easy to add Open Document Format (ODF) support to your website and to your mobile or desktop application. It uses HTML and CSS to display ODF documents.</description>
			</info>
			<files>
				<client>
					<clientfile load = "debug">lib/webodf-debug.js</clientfile>
					<clientfile load = "release">lib/webodf.js</clientfile>
				</client>
			</files>
		</component>
		<component>
			<info>
				<name>webodfboxplugin</name>
				<title>WebOdfPlugin</title>
				<author>Zarafa</author>
				<description>A Zarafa plugin enabling the use of WebOdfBox for opening ODT, ODP, ODS attachments in e-mails.</description>
			</info>
			<files>
				<server>
					<serverfile>php/plugin.webodfbox.php</serverfile>
				</server>
				<client>
					<clientfile load = "release">js/webodf.js</clientfile>
					<clientfile load = "debug">js/webodf-debug.js</clientfile>
					<clientfile load = "source">js/WebOdfPlugin.js</clientfile>
					<clientfile load = "source">js/ABOUT.js</clientfile>
					<clientfile load = "source">js/WebOdfBox.js</clientfile>
				</client>
				<resources>
					<resourcefile>resources/css/webodf.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/sugarcrm/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.2</version>
		<name>SugarCRM</name>
		<title>SugarCRM Webapp Archive</title>
		<author>Sebastian Kummer</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Archive selected record to the SugarCRM</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<components>
		<component>
			<files>
				<server>
					<serverfile>php/plugin.sugarcrm.php</serverfile>
					<serverfile type="module" module="sugarcrmmodule">php/class.sugarcrmmodule.php</serverfile>
				</server>
				<client>
					<clientfile load="release">js/sugarcrm.js</clientfile>
					<clientfile load="debug">js/sugarcrm-debug.js</clientfile>
					<clientfile load="source">js/SugarCRMPlugin.js</clientfile>
					<clientfile load="source">js/data/SugarCRMResponseHandler.js</clientfile>
					<clientfile load="source">js/ABOUT.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/sugarcrm.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>

=== jelly/zarafa-webapp/plugins/files/manifest.xml
<?xml version="1.0"?>
<!DOCTYPE plugin SYSTEM "manifest.dtd">
<plugin version="2">
	<info>
		<version>0.1</version>
		<name>files</name>
		<title>Files Integration</title>
		<author>Zarafa</author>
		<authorURL>http://www.zarafa.com</authorURL>
		<description>Integrate Files into Zarafa Webapp</description>
	</info>
	<config>
		<configfile>config.php</configfile>
	</config>
	<translations>
		<translationsdir>languages</translationsdir>
	</translations>
	<components>
		<component>
			<files>
				<server>
					<serverfile type="module" module="filesmodule">php/class.filesmodule.php</serverfile>
					<serverfile type="module" module="filesbrowsermodule">php/class.filesbrowsermodule.php</serverfile>
					<serverfile>php/plugin.files.php</serverfile>
				</server>
				<client>
					<clientfile load="release">php/jsloader.php?debug=false</clientfile>
					<clientfile load="debug">php/jsloader.php?debug=true</clientfile>
					
					<clientfile load="source">js/ABOUT.js</clientfile>
					<clientfile load="source">js/data/ResponseHandler.js</clientfile>
					<clientfile load="source">js/data/DirectoryLoader.js</clientfile>
					<clientfile load="source">js/data/Version.js</clientfile>
					<clientfile load="source">js/data/Dynamics.js</clientfile>
					<clientfile load="source">js/settings/SettingsFilesComponentsWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsFilesWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsFilesVersionWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsFilesQuotaWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsFilesResetSettingsWidget.js</clientfile>
					<clientfile load="source">js/settings/SettingsFilesCategory.js</clientfile>
					<clientfile load="source">js/dialogs/AttachFromFilesTreePanel.js</clientfile>
					<clientfile load="source">js/dialogs/AttachFromFilesContentPanel.js</clientfile>
					<clientfile load="source">js/dialogs/SaveToFilesTreePanel.js</clientfile>
					<clientfile load="source">js/dialogs/SaveToFilesContentPanel.js</clientfile>
					<clientfile load="source">js/AttachFromFilesPlugin.js</clientfile>
					<clientfile load="source">js/SaveToFilesPlugin.js</clientfile>
					<!-- Context includes -->
					<clientfile load="source">js/data/Helper.js</clientfile>
					<clientfile load="source">js/data/ComponentBox.js</clientfile>
					<clientfile load="source">js/data/DataModes.js</clientfile>
					<clientfile load="source">js/data/FileTypes.js</clientfile>
					<clientfile load="source">js/data/ViewModes.js</clientfile>
					<clientfile load="source">js/data/Views.js</clientfile>
					<clientfile load="source">js/data/Actions.js</clientfile>
					<clientfile load="source">js/data/FilesRecord.js</clientfile>
					<clientfile load="source">js/data/FilesStore.js</clientfile>
					<clientfile load="source">js/dialogs/ShowFilesFileContentPanel.js</clientfile>
					<clientfile load="source">js/dialogs/FilesUploadContentPanel.js</clientfile>
					<clientfile load="source">js/ui/UploadButton.js</clientfile>
					<clientfile load="source">js/ui/UploadPanel.js</clientfile>
					<clientfile load="source">js/ui/NavigatorTreePanel.js</clientfile>
					<clientfile load="source">js/ui/FilesViewPanel.js</clientfile>
					<clientfile load="source">js/ui/FilesFileInfo.js</clientfile>
					<clientfile load="source">js/ui/FilesPreviewPanelToolbarButtons.js</clientfile>
					<clientfile load="source">js/ui/FilesToolbar.js</clientfile>
					<clientfile load="source">js/ui/FilesPreviewPanel.js</clientfile>
					<clientfile load="source">js/ui/FilesFileGridColumnModel.js</clientfile>
					<clientfile load="source">js/ui/FilesFileGridContextMenu.js</clientfile>
					<clientfile load="source">js/ui/FilesFileGrid.js</clientfile>
					<clientfile load="source">js/ui/FilesIconView.js</clientfile>
					<clientfile load="source">js/ui/FilesMainPanel.js</clientfile>
					<clientfile load="source">js/ui/ExtTreepanelOverrides.js</clientfile>
					<clientfile load="source">js/ui/QuotaBar.js</clientfile>
					<clientfile load="source">js/context/FilesContextModel.js</clientfile>
					<clientfile load="source">js/context/FilesContext.js</clientfile>
					<!-- Main Loader -->
					<clientfile load="source">js/FilesPlugin.js</clientfile>
				</client>
				<resources>
					<resourcefile load="release">resources/css/files-min.css</resourcefile>
					<resourcefile load="debug">resources/css/files.css</resourcefile>
					
					<resourcefile load="source">resources/css/files-main.css</resourcefile>
				</resources>
			</files>
		</component>
	</components>
</plugin>
